version: 2
updates:
  - package-ecosystem: npm
    directory: /web
    schedule: { interval: weekly }
    open-pull-requests-limit: 5
    groups:
      frontend-minor:
        update-types: [minor, patch]

  - package-ecosystem: gradle
    directory: /server
    schedule: { interval: weekly }
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /
    schedule: { interval: weekly }
    open-pull-requests-limit: 5
